CREATE TABLE `vehicles` (
	`id` int AUTO_INCREMENT NOT NULL,
	`slug` varchar(160) NOT NULL,
	`type` enum('car','motorcycle','minibus') NOT NULL,
	`make` varchar(80) NOT NULL,
	`model` varchar(120) NOT NULL,
	`year` int NOT NULL,
	`price` int NOT NULL,
	`mileage` int NOT NULL,
	`fuel` varchar(40) NOT NULL,
	`transmission` varchar(40) NOT NULL,
	`engine` varchar(40) NOT NULL,
	`drive` varchar(40),
	`color` varchar(40),
	`location` varchar(80) NOT NULL DEFAULT 'Кишинёв',
	`condition` varchar(40) NOT NULL DEFAULT 'В наличии',
	`status` enum('available','reserved','sold') NOT NULL DEFAULT 'available',
	`featured` int NOT NULL DEFAULT 0,
	`imageUrl` text NOT NULL,
	`description` text NOT NULL,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `vehicles_id` PRIMARY KEY(`id`),
	CONSTRAINT `vehicles_slug_unique` UNIQUE(`slug`)
);
