import { useState } from "react";
import { Link, useRoute } from "wouter";
import { ArrowLeft, ChevronLeft, ChevronRight, Phone } from "lucide-react";
import { getVehicles } from "@/data/vehicles";

export default function VehicleDetail() {
  const [, params] = useRoute("/vehicle/:slug");
  const vehicle = getVehicles().find((item) => item.slug === params?.slug);
  const [image, setImage] = useState(0); const [name, setName] = useState(""); const [phone, setPhone] = useState(""); const [status, setStatus] = useState("");
  if (!vehicle) return <div className="grid min-h-screen place-items-center bg-[#0d0d0f]"><Link href="/" className="font-bold text-[#d71920]">Вернуться в каталог</Link></div>;
  const photos = vehicle.imageUrls?.length ? vehicle.imageUrls : [vehicle.imageUrl];
  const submit = async (event: React.FormEvent) => { event.preventDefault(); setStatus("Отправляем…"); try { const response = await fetch("/api/lead", { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ name, phone, vehicle: `${vehicle.make} ${vehicle.model}` }) }); setStatus(response.ok ? "Спасибо! Мы получили вашу заявку." : "Не удалось отправить заявку. Позвоните нам напрямую."); } catch { setStatus("Не удалось отправить заявку. Позвоните нам напрямую."); } };
  return <main className="min-h-screen bg-[#0d0d0f]"><header className="border-b border-[#2b2b30]"><div className="container flex h-[74px] items-center justify-between"><Link href="/" className="font-extrabold tracking-[.18em]">SUD AUTO PARK</Link><a href="tel:+37369999999" className="rounded-full bg-[#d71920] px-4 py-2 text-sm font-bold">Позвонить</a></div></header><div className="container py-8 md:py-12"><Link href="/" className="mb-7 inline-flex items-center gap-2 font-bold text-[#d71920]"><ArrowLeft className="h-4 w-4" /> Назад к каталогу</Link><div className="grid gap-8 md:grid-cols-2"><section><div className="relative overflow-hidden rounded-[28px] bg-[#17171a]"><img src={photos[image]} alt={`${vehicle.make} ${vehicle.model}`} className="aspect-[1.2/1] w-full object-cover" />{photos.length > 1 && <><button onClick={() => setImage((image + photos.length - 1) % photos.length)} className="absolute left-4 top-1/2 -translate-y-1/2 rounded-full bg-black/60 p-3"><ChevronLeft /></button><button onClick={() => setImage((image + 1) % photos.length)} className="absolute right-4 top-1/2 -translate-y-1/2 rounded-full bg-black/60 p-3"><ChevronRight /></button></>}</div><div className="mt-3 flex gap-3">{photos.map((photo, index) => <button key={photo} onClick={() => setImage(index)} className={`h-20 w-24 overflow-hidden rounded-xl ${image === index ? "ring-2 ring-[#d71920]" : "opacity-60"}`}><img src={photo} alt="" className="h-full w-full object-cover" /></button>)}</div></section><section className="rounded-[28px] bg-[#17171a] p-7 md:p-9"><p className="eyebrow">{vehicle.type === "car" ? "АВТОМОБИЛЬ" : vehicle.type === "motorcycle" ? "МОТОЦИКЛ" : "МИКРОАВТОБУС"} · В НАЛИЧИИ</p><h1 className="mt-3 text-4xl font-extrabold md:text-5xl">{vehicle.make}<br />{vehicle.model}</h1><p className="mt-5 text-3xl font-extrabold text-[#d71920]">€{new Intl.NumberFormat("ru-RU").format(vehicle.price)}</p><p className="mt-5 text-[#a6a6ad]">{vehicle.description}</p><div className="my-7 grid grid-cols-2 gap-3 border-y border-[#2b2b30] py-5 text-sm"><p>Год<br /><b>{vehicle.year}</b></p><p>Пробег<br /><b>{new Intl.NumberFormat("ru-RU").format(vehicle.mileage)} км</b></p><p>Топливо<br /><b>{vehicle.fuel}</b></p><p>Коробка<br /><b>{vehicle.transmission}</b></p></div><form onSubmit={submit} className="grid gap-3"><h2 className="text-xl font-extrabold">Оставить заявку</h2><input required value={name} onChange={(event) => setName(event.target.value)} placeholder="Ваше имя" className="rounded-xl bg-[#242428] p-3 outline-none" /><input required value={phone} onChange={(event) => setPhone(event.target.value)} placeholder="Телефон" type="tel" className="rounded-xl bg-[#242428] p-3 outline-none" /><button className="inline-flex items-center justify-center gap-2 rounded-xl bg-[#d71920] p-4 font-bold"><Phone className="h-4 w-4" /> Отправить заявку</button>{status && <p className="text-sm text-[#a6a6ad]">{status}</p>}</form></section></div></div></main>;
}
